name: blackjack
description: A new Flutter project.

dependencies:
  meta: "^1.1.2"
  quiver: '>=0.28.0 <0.30.0'
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  path: "^1.5.1"
  image: "^1.1.31"
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - images/2c.gif
    - images/2d.gif
    - images/2h.gif
    - images/2s.gif
    - images/3c.gif
    - images/3d.gif
    - images/3h.gif
    - images/3s.gif
    - images/4c.gif
    - images/4d.gif
    - images/4h.gif
    - images/4s.gif
    - images/5c.gif
    - images/5d.gif
    - images/5h.gif
    - images/5s.gif
    - images/6c.gif
    - images/6d.gif
    - images/6h.gif
    - images/6s.gif
    - images/7c.gif
    - images/7d.gif
    - images/7h.gif
    - images/7s.gif
    - images/8c.gif
    - images/8d.gif
    - images/8h.gif
    - images/8s.gif
    - images/9c.gif
    - images/9d.gif
    - images/9h.gif
    - images/9s.gif
    - images/ac.gif
    - images/ad.gif
    - images/ah.gif
    - images/as.gif
    - images/jc.gif
    - images/jd.gif
    - images/jh.gif
    - images/js.gif
    - images/kc.gif
    - images/kd.gif
    - images/kh.gif
    - images/ks.gif
    - images/qc.gif
    - images/qd.gif
    - images/qh.gif
    - images/qs.gif
    - images/tc.gif
    - images/td.gif
    - images/th.gif
    - images/ts.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
